SCENE_WIDTH = 156
SCENE_HEIGHT = 38
TOWN_HALL_HEIGHT = 4
TOWN_HALL_WIDTH = 3
TOWN_HALL_HITPOINTS = 1000

CANNON_WIDTH = 3
CANNON_HEIGHT = 2
CANNON_HITPOINTS = 700
CANNON_RANGE = 10
CANNON_DAMAGE = 10
CANNON_ATTACK_DELAY = 1

BUILDER_HUT_WIDTH = 2
BUILDER_HUT_HEIGHT = 2
BUILDER_HUT_HITPOINTS = 600
BUILDING_RECOMPUTE_TIME = 5

WALL_WIDTH = 1
WALL_HEIGHT = 1
WALL_HITPOINTS = 200

SPAWN_WIDTH = 2
SPAWN_HEIGHT = 2

KING_HEALTH = 100
KING_DAMAGE = 100
KING_ATTACK_DELAY = 1

BARBARIANS_HEALTH = 13
BARBARIANS_ATTACK_DELAY = 1

HEAL_SPELL_LIMIT =2 
RAGE_SPELL_LIMIT = 1

HEALTH_MULTIPLIER = 1.5
RAGE_MULTIPLIER = 2
RAGE_TIME = 5

REFRESH_RATE = 100

MAX_BARBARIANS = 10
MAX_ARCHERS = 6
MAX_BALLOONS = 4

EAGLE_ARROW_COOLDOWN = 1